#!/usr/bin/env python
import roslib
roslib.load_manifest('figleaf_2d')
import sys
import rospy
import cv2
import cv
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
import random
import numpy as np

import message_filters2
import image_filtering as filt
from skimage.segmentation import slic as slic_seg

class image_converter:

  def __init__(self):
    self.image_pub = rospy.Publisher("image_topic_2",Image)
    self.skipped = 0
    print('initializing')

#    image_sub = message_filters.Subscriber('image', Image)
#    info_sub = message_filters.Subscriber('camera_info', CameraInfo)

#    ts = message_filters.TimeSynchronizer([image_sub, info_sub], 10)
#    ts.registerCallback(callback)

    cv2.namedWindow("Image window", 1)
    self.bridge = CvBridge()

#    self.image_sub = rospy.Subscriber("/head_mount_kinect/rgb/image_color", Image, self.callback, queue_size=1)
    self.image_sub = message_filters2.Subscriber("/head_mount_kinect/rgb/image_color", Image)
    self.depth_sub = message_filters2.Subscriber("/head_mount_kinect/depth_registered/image_rect", Image)
    self.time_sync = message_filters2.ApproximateTimeSynchronizer([self.image_sub, self.depth_sub], 5, 0.2)
    self.time_sync.registerCallback(self.callback)

  def callback(self, image_data, depth_data):
    print('callback')
    try:
        cv_image = self.bridge.imgmsg_to_cv2(image_data, "bgr8")            
        cv_depth = self.bridge.imgmsg_to_cv2(depth_data, "passthrough")
    except CvBridgeError, e:
        print e

    if self.skipped == 2:
        print('  processing')

        cv_out_image = filt.slic(cv_image, sigma=3, compactness=15, n_segments=400)
        cv_out_image[np.squeeze(np.logical_or(np.isnan(cv_depth), cv_depth < .7))] = 0
        
#        cv_image2 = filt.inverted_hue_of_slic_of_gaussian(cv_image)
        self.skipped = 0

        cv2.imshow("Image window", cv_out_image)
        cv2.waitKey(3)
        try:
            self.image_pub.publish(self.bridge.cv2_to_imgmsg(cv_out_image, "passthrough"))
        except CvBridgeError, e:
            print e
    else:
        print('  skipping')
        self.skipped += 1


def main(args):
  ic = image_converter()
  rospy.init_node('image_converter', anonymous=True)
  try:
    rospy.spin()
  except KeyboardInterrupt:
    print "Shutting down"
  cv2.destroyAllWindows()

if __name__ == '__main__':
    main(sys.argv)

